version: '3.9'

services:
  api:
    build:
      context: ./api
    container_name: 'api'
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app

  web:
    build:
      context: ./web
    container_name: 'web'
    ports:
      - 3001
    depends_on:
      - api
      - postgres
    volumes:
      - ./web:/app

  postgres:
    image: 'postgres:14-alpine'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authentication
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: 'redis:7-alpine'
    container_name: 'redis'
    ports:
      - 6379:6379
volumes:
  postgres_data:


